matrix:
  include:
    - language: ruby
      rvm:
        - 2.3
        - 2.4
        - 2.5
      before_install:
        - gem update --system
        - gem install bundler
      script:
        - bundle exec rubocop
        - bundle exec rspec

    - language: node_js
      node_js:
        - node
      script:
        - yarn run stylelint
        - yarn run eslint
      cache:
        yarn: true
        directories:
          - node_modules
